import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";

function NotFoundComponent(){return <div className="flex min-h-svh items-center justify-center bg-background px-6"><div className="text-center"><p className="font-editorial text-7xl font-semibold">404</p><h1 className="mt-4 text-xl font-extrabold">Esta oportunidade já não está aqui.</h1><p className="mt-2 text-sm text-muted-foreground">Pode ter terminado ou mudado de endereço.</p><Button asChild className="mt-6"><Link to="/">Ver novidades</Link></Button></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="flex min-h-svh items-center justify-center bg-background px-6"><div className="text-center"><h1 className="text-xl font-extrabold">Esta página não abriu.</h1><p className="mt-2 text-sm text-muted-foreground">Tenta novamente dentro de alguns segundos.</p><Button className="mt-6" onClick={()=>{router.invalidate();reset()}}>Tentar novamente</Button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1, viewport-fit=cover"},{name:"theme-color",content:"#173F32"},{name:"author",content:"Beer Money Club"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700&family=Outfit:wght@500;600;700;800&display=swap"},{rel:"icon",type:"image/png",href:"/favicon.png"},{rel:"apple-touch-icon",href:"/icons/apple-touch-icon.png"},{rel:"manifest",href:"/manifest.webmanifest"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="pt"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const{queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><Outlet/></QueryClientProvider>}
