import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, Check, Clock3, Hourglass, Sparkles } from "lucide-react";
import { AppShell } from "@/components/beer-money/app-shell";

export const Route = createFileRoute("/alertas")({ head: () => ({ meta: [{ title: "A tua atividade — Beer Money Club" },{ name: "description", content: "Acompanha oportunidades concluídas, pendentes e recompensas disponíveis." },{ property: "og:title", content: "A tua atividade — Beer Money Club" },{ property: "og:description", content: "Progresso pessoal e mudanças importantes nas tuas oportunidades." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: AlertsPage });
const events=[
 {time:"Agora",title:"Coinbase aumentou para 20€",text:"A recompensa anterior era 10€.",icon:ArrowUpRight,id:"coinbase-recompensa"},
 {time:"Há 42 min",title:"Nova campanha AttaPoll",text:"Novos inquéritos pagos estão disponíveis.",icon:Sparkles,id:"atapoll-inqueritos"},
 {time:"Amanhã",title:"Cashback de lojas termina",text:"Último dia para ativar a campanha.",icon:Clock3,id:"cashback-lojas"},
];
const activity=[{brand:"Coinbase",state:"Concluída",detail:"20€ confirmados",icon:Check},{brand:"MyFin",state:"Concluída",detail:"20€ recebidos",icon:Check},{brand:"Kraken",state:"Pendente",detail:"A aguardar validação",icon:Hourglass},{brand:"Robinhood",state:"Em espera",detail:"5 meses restantes",icon:Clock3},{brand:"Bybit",state:"Disponível",detail:"Recompensa pronta",icon:Sparkles}];
 function AlertsPage(){return <AppShell title="Alertas" eyebrow="O teu progresso"><div className="px-5 pt-5"><section><p className="eyebrow">A minha atividade</p><h2 className="mt-1.5 text-[22px] font-bold">Em andamento</h2><div className="mt-3">{activity.map(({brand,state,detail,icon:Icon})=><div key={brand} className="activity-row"><span className="activity-icon"><Icon/></span><div className="min-w-0 flex-1"><p className="text-[15px] font-bold">{brand}</p><p className="mt-0.5 text-xs text-muted-foreground">{detail}</p></div><span className="text-xs font-semibold text-primary">{state}</span></div>)}</div></section><section className="pb-4 pt-9"><p className="eyebrow">Mudanças importantes</p><h2 className="mt-1.5 text-[22px] font-bold">A não perder</h2><div className="mt-3">{events.map(({time,title,text,icon:Icon,id})=><Link key={title} to="/oportunidades/$id" params={{id}} className="alert-row"><Icon className="mt-1 size-5 flex-none text-primary"/><div><p className="text-[10px] font-bold uppercase text-muted-foreground">{time}</p><h3 className="mt-1 text-[15px] font-bold">{title}</h3><p className="mt-1 text-[13px] leading-5 text-muted-foreground">{text}</p></div></Link>)}</div></section></div></AppShell>}
