import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, BellRing, Clock3, Sparkles } from "lucide-react";
import { AppShell } from "@/components/beer-money/app-shell";

export const Route = createFileRoute("/alertas")({ head: () => ({ meta: [{ title: "Alertas — Beer Money Club" },{ name: "description", content: "Histórico das oportunidades novas, aumentos e prazos importantes." },{ property: "og:title", content: "Alertas — Beer Money Club" },{ property: "og:description", content: "Tudo o que mudou, numa timeline simples." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: AlertsPage });
const events=[
 {time:"Agora",title:"Bybit aumentou para 50€",text:"Antes eram 20€. A campanha foi atualizada.",icon:ArrowUpRight,id:"bybit-bonus-50",tone:"bg-positive-soft text-positive"},
 {time:"Há 42 min",title:"Nova oportunidade: Perplexity",text:"Acesso Pro em campanha por tempo limitado.",icon:Sparkles,id:"perplexity-pro",tone:"bg-gold-soft text-foreground"},
 {time:"Ontem, 21:10",title:"Vinted termina hoje",text:"Últimas horas para aproveitar os envios selecionados.",icon:Clock3,id:"vinted-portes",tone:"bg-urgent-soft text-urgent"},
];
function AlertsPage(){return <AppShell title="Alertas" eyebrow="O que mudou" action={<span className="grid size-9 place-items-center rounded-full bg-accent text-xs font-extrabold text-primary">3</span>}><div className="px-5 pt-5"><div className="mb-7 flex items-center gap-3 rounded-xl bg-primary px-4 py-4 text-primary-foreground"><BellRing className="size-5"/><div><p className="text-sm font-extrabold">Alertas relevantes, sem ruído</p><p className="text-xs opacity-75">Só avisamos quando vale mesmo a pena.</p></div></div><div className="relative ml-5 border-l border-border pl-7">{events.map(({time,title,text,icon:Icon,id,tone})=><Link key={title} to="/oportunidades/$id" params={{id}} className="relative mb-8 block"><span className={`absolute -left-[46px] top-0 grid size-9 place-items-center rounded-full ring-4 ring-background ${tone}`}><Icon className="size-4"/></span><p className="text-[11px] font-bold uppercase text-muted-foreground">{time}</p><h2 className="mt-1 text-[16px] font-extrabold">{title}</h2><p className="mt-1 text-sm leading-5 text-muted-foreground">{text}</p></Link>)}</div><div className="rounded-xl bg-muted px-4 py-5 text-center"><p className="font-extrabold">Estás em dia</p><p className="mt-1 text-sm text-muted-foreground">Viste todas as mudanças desde a última visita.</p></div></div></AppShell>}
