import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Bell, Bookmark, ChevronRight, Download, History, LogOut, MessageCircle, Settings } from "lucide-react";
import { AppShell } from "@/components/beer-money/app-shell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/conta")({ head: () => ({ meta: [{ title:"Conta — Beer Money Club"},{name:"description",content:"Preferências, oportunidades guardadas e histórico."},{property:"og:title",content:"Conta — Beer Money Club"},{property:"og:description",content:"Gere os teus alertas e oportunidades guardadas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: AccountPage });
const rows=[{icon:Bell,label:"Preferências de alertas",detail:"Só o que é relevante"},{icon:Bookmark,label:"Guardadas",detail:"3 oportunidades"},{icon:History,label:"Histórico",detail:"Vistas e concluídas"},{icon:MessageCircle,label:"Comunidade Discord",detail:"Conversas e ajuda"},{icon:Settings,label:"Definições",detail:"Privacidade e dados"}];
function AccountPage(){const navigate=useNavigate();async function logout(){await supabase.auth.signOut();navigate({to:"/login"})}return <AppShell title="Conta" eyebrow="O teu espaço"><section className="px-5 pt-5"><div className="flex items-center gap-4 border-b pb-6"><div className="grid size-14 place-items-center rounded-lg bg-primary text-lg font-extrabold text-primary-foreground">BM</div><div><h2 className="font-extrabold">Membro do Club</h2><p className="text-sm text-muted-foreground">Portugal</p></div></div><div className="py-4"><Button asChild variant="outline" className="h-12 w-full justify-between"><Link to="/instalar"><span className="flex items-center gap-3"><Download className="text-primary"/>Adicionar ao ecrã principal</span><ChevronRight/></Link></Button></div><div className="divide-y">{rows.map(({icon:Icon,label,detail})=><button key={label} className="flex w-full items-center gap-3 py-4 text-left"><Icon className="size-5 text-primary"/><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">{label}</span><span className="block text-xs text-muted-foreground">{detail}</span></span><ChevronRight className="size-4 text-muted-foreground"/></button>)}</div><Button variant="ghost" className="mt-6 w-full text-muted-foreground" onClick={logout}><LogOut/>Terminar sessão</Button></section></AppShell>}
