import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { Bell, Bookmark, ChevronRight, Download, FileText, HandCoins, History, LogOut, MessageCircle, Settings } from "lucide-react";
import { AppShell } from "@/components/beer-money/app-shell";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/conta")({ head: () => ({ meta: [{ title:"Conta — Beer Money App"},{name:"description",content:"Preferências, oportunidades guardadas e histórico."},{property:"og:title",content:"Conta — Beer Money App"},{property:"og:description",content:"Gere os teus alertas e oportunidades guardadas."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: AccountPage });
const rows=[{icon:Bell,label:"Preferências de alertas",detail:"Só o que é relevante"},{icon:Bookmark,label:"Guardadas",detail:"[PREENCHER]"},{icon:History,label:"Histórico",detail:"Vistas e concluídas"},{icon:MessageCircle,label:"Comunidade",detail:"Discord"},{icon:Settings,label:"Definições",detail:"Privacidade e dados"}];
function AccountPage(){const navigate=useNavigate();async function logout(){await supabase.auth.signOut();navigate({to:"/login"})}return <AppShell title="Conta" eyebrow="Definições pessoais"><section className="px-5 pt-5"><div className="flex items-center gap-4 border-b pb-6"><div className="account-monogram">BM</div><div><h2 className="font-extrabold">Utilizador Beer Money</h2><p className="text-sm text-muted-foreground">Portugal</p></div></div><div className="py-4"><Button asChild variant="outline" className="h-12 w-full"><Link to="/instalar"><Download/>Adicionar ao ecrã principal</Link></Button></div><div className="divide-y">{rows.map(({icon:Icon,label,detail})=><Button key={label} variant="ghost" className="account-row h-auto rounded-none px-0"><Icon className="size-5"/><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">{label}</span><span className="block text-xs text-muted-foreground">{detail}</span></span><ChevronRight className="size-4 text-muted-foreground"/></Button>)}<Button asChild variant="ghost" className="account-row h-auto rounded-none px-0"><Link to="/como-ganhamos-dinheiro"><HandCoins className="size-5"/><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">Como ganhamos dinheiro</span><span className="block text-xs text-muted-foreground">Relações comerciais e comissões</span></span><ChevronRight className="size-4 text-muted-foreground"/></Link></Button><Button asChild variant="ghost" className="account-row h-auto rounded-none px-0"><Link to="/informacao-legal"><FileText className="size-5"/><span className="min-w-0 flex-1"><span className="block text-sm font-extrabold">Informação legal</span><span className="block text-xs text-muted-foreground">Entidade, privacidade e suporte</span></span><ChevronRight className="size-4 text-muted-foreground"/></Link></Button></div><Button variant="ghost" className="mt-6 w-full text-muted-foreground" onClick={logout}><LogOut/>Terminar sessão</Button></section></AppShell>}
