import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { BellRing, ChevronRight, MoreVertical, Share, SquarePlus } from "lucide-react";
import { useEffect, useState } from "react";
import { Brand } from "@/components/beer-money/brand";
import { Button } from "@/components/ui/button";

declare global { interface WindowEventMap { beforeinstallprompt: Event; } }
type InstallPromptEvent = Event & { prompt:()=>Promise<void>; userChoice:Promise<{outcome:"accepted"|"dismissed"}> };
export const Route = createFileRoute("/instalar")({ head: () => ({ meta: [{ title: "Instalar — Beer Money Club" },{ name: "description", content: "Adiciona o Beer Money Club ao ecrã principal em três passos." },{ property: "og:title", content: "Instalar Beer Money Club" },{ property: "og:description", content: "Acesso num toque e alertas como numa aplicação normal." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: InstallPage });
function InstallPage(){const [prompt,setPrompt]=useState<InstallPromptEvent|null>(null);const navigate=useNavigate();useEffect(()=>{const handler=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPromptEvent)};window.addEventListener("beforeinstallprompt",handler);return()=>window.removeEventListener("beforeinstallprompt",handler)},[]);async function install(){if(prompt){await prompt.prompt();await prompt.userChoice}navigate({to:"/"})}return <main className="mx-auto flex min-h-svh max-w-[540px] flex-col bg-background px-5 pb-[max(24px,env(safe-area-inset-bottom))] pt-6"><Brand/><div className="flex flex-1 flex-col justify-center py-8"><div className="mx-auto mb-8 grid size-28 place-items-center rounded-[28px] bg-primary text-primary-foreground shadow-xl"><BellRing className="size-12" strokeWidth={1.5}/></div><div className="text-center"><p className="eyebrow">NÃO PERCAS A PRÓXIMA</p><h1 className="mt-3 font-editorial text-[38px] font-semibold leading-none">Leva o Club contigo.</h1><p className="mx-auto mt-4 max-w-sm leading-6 text-muted-foreground">Abre num toque e recebe alertas como numa aplicação normal.</p></div><ol className="mt-9 space-y-3">{[[Share,"Toca em Partilhar","Na barra do navegador"],[SquarePlus,"Adicionar ao Ecrã Principal","Escolhe esta opção no menu"],[MoreVertical,"Confirma em Adicionar","O ícone fica pronto a usar"]].map(([Icon,title,text],i)=><li key={String(title)} className="flex items-center gap-4 rounded-xl border bg-card p-4"><span className="grid size-10 place-items-center rounded-full bg-accent text-sm font-extrabold text-primary">{i+1}</span><div className="flex-1"><p className="text-sm font-extrabold">{String(title)}</p><p className="mt-0.5 text-xs text-muted-foreground">{String(text)}</p></div>{typeof Icon!=="string"&&<Icon className="size-5 text-primary"/>}</li>)}</ol></div><div className="space-y-2"><Button size="lg" className="h-13 w-full text-base" onClick={install}>{prompt?"Adicionar agora":"Já percebi"}<ChevronRight/></Button><Button variant="ghost" className="w-full text-muted-foreground" onClick={()=>navigate({to:"/"})}>Agora não</Button></div></main>}
