import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Apple, Loader2 } from "lucide-react";
import { useState } from "react";
import { Brand } from "@/components/beer-money/brand";
import { Button } from "@/components/ui/button";
import { lovable } from "@/integrations/lovable/index";

export const Route = createFileRoute("/login")({ head: () => ({ meta: [{ title: "Entrar — Beer Money Club" },{ name: "description", content: "Entra com Google ou Apple no Beer Money Club." },{ property: "og:title", content: "Entrar — Beer Money Club" },{ property: "og:description", content: "A tua lista de oportunidades, sempre contigo." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: LoginPage });
function GoogleMark(){return <span className="text-base font-black text-primary">G</span>}
function LoginPage(){const [loading,setLoading]=useState<"google"|"apple"|null>(null);const [error,setError]=useState("");const navigate=useNavigate();async function signIn(provider:"google"|"apple"){setLoading(provider);setError("");const result=await lovable.auth.signInWithOAuth(provider,{redirect_uri:window.location.origin});if(result.error){setError("Não foi possível entrar. Tenta novamente.");setLoading(null);return}if(!result.redirected)navigate({to:"/instalar"})}
return <main className="mx-auto flex min-h-svh max-w-[540px] flex-col bg-background px-6 pb-[max(24px,env(safe-area-inset-bottom))] pt-6"><Brand/><div className="flex flex-1 flex-col justify-center"><div className="mb-10"><p className="eyebrow">A TUA CONTA</p><h1 className="mt-3 text-[42px] font-extrabold leading-none">As oportunidades<br/>esperam por ti.</h1><p className="mt-4 max-w-sm text-base leading-6 text-muted-foreground">Entra para guardar oportunidades e receber alertas relevantes.</p></div><div className="space-y-3"><Button variant="outline" size="lg" className="h-14 w-full justify-center bg-card text-base" onClick={()=>signIn("google")} disabled={loading!==null}>{loading==="google"?<Loader2 className="animate-spin"/>:<GoogleMark/>}Continuar com Google</Button><Button size="lg" className="h-14 w-full justify-center text-base" onClick={()=>signIn("apple")} disabled={loading!==null}>{loading==="apple"?<Loader2 className="animate-spin"/>:<Apple className="fill-current"/>}Continuar com Apple</Button></div>{error&&<p className="mt-4 text-center text-sm text-destructive">{error}</p>}<p className="mt-7 text-center text-xs leading-5 text-muted-foreground">Ao continuar, aceitas os Termos e a Política de Privacidade.</p></div></main>}
