import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { BellRing, ChevronRight, Clock3, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { Brand } from "@/components/beer-money/brand";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/onboarding")({ head: () => ({ meta: [{ title: "Bem-vindo — Beer Money App" },{ name: "description", content: "Cashback, bónus e recompensas num só lugar." },{ property: "og:title", content: "Cashback, bónus e recompensas" },{ property: "og:description", content: "As melhores oportunidades para ganhar dinheiro extra num só lugar." },{ property: "og:type", content: "website" },{ name: "twitter:card", content: "summary_large_image" }] }), component: OnboardingPage });
const pages=[
 {title:"Cashback, bónus e recompensas.",text:"As melhores oportunidades para ganhar dinheiro extra num só lugar.",visual:<div className="grid size-40 place-items-center rounded-full bg-accent text-primary"><Sparkles className="size-16" strokeWidth={1.4}/></div>},
 {title:"As melhores oportunidades não esperam.",text:"Milhares de oportunidades desaparecem todos os dias.",visual:<div className="w-full max-w-[300px] animate-pulse rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><strong>Cashback especial</strong><strong className="text-2xl">35€</strong></div><div className="mt-5 flex items-center gap-2 text-sm text-urgent"><Clock3 className="size-4"/> Termina em breve</div></div>},
 {title:"Nós avisamos-te primeiro.",text:"Só quando há uma mudança que merece a tua atenção.",visual:<div className="w-full max-w-[320px] rounded-2xl bg-foreground p-4 text-background shadow-2xl"><div className="flex gap-3"><span className="grid size-10 place-items-center rounded-xl bg-gold-soft text-foreground"><BellRing className="size-5"/></span><div><p className="text-xs opacity-60">BEER MONEY APP · AGORA</p><p className="mt-1 font-extrabold">Bybit aumentou para 50€</p></div></div></div>},
 {title:"Disponíveis neste momento.",text:"Tudo organizado. Sem ruído, sem oportunidades escondidas.",visual:<div className="text-center"><p className="big-number motion-count">287€</p><p className="mt-4 text-sm font-bold text-muted-foreground">8 oportunidades verificadas</p></div>}
];
function OnboardingPage(){const [step,setStep]=useState(0);const navigate=useNavigate();useEffect(()=>{localStorage.setItem("bmc-seen-onboarding","1")},[]);const p=pages[step];if(!p)return null;return <main className="mx-auto flex min-h-svh max-w-[540px] flex-col bg-background px-6 pb-[max(24px,env(safe-area-inset-bottom))] pt-6"><Brand/><div className="flex flex-1 flex-col items-center justify-center py-8"><div key={step} className="motion-rise flex min-h-[250px] w-full items-center justify-center">{p.visual}</div><div key={`copy-${step}`} className="motion-rise mt-8 text-center"><h1 className="font-editorial text-[38px] font-semibold leading-[1.02]">{p.title}</h1><p className="mx-auto mt-4 max-w-sm text-[16px] leading-6 text-muted-foreground">{p.text}</p></div></div><div><div className="mb-5 flex justify-center gap-2">{pages.map((_,i)=><span key={i} className={i===step?"h-1.5 w-7 rounded-full bg-primary":"size-1.5 rounded-full bg-border"}/>)}</div><Button size="lg" className="h-13 w-full text-base" onClick={()=>step===pages.length-1?navigate({to:"/login"}):setStep(step+1)}>{step===pages.length-1?"Começar":"Continuar"}<ChevronRight/></Button></div></main>}
