import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Bell, Bookmark, Check, Clock3, ExternalLink, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { opportunities } from "@/lib/opportunities";

export const Route = createFileRoute("/oportunidades/$id")({
  loader: ({ params }) => { const item=opportunities.find(o=>o.id===params.id); if(!item) throw notFound(); return item; },
  head: ({ loaderData }) => ({ meta: loaderData ? [{ title: `${loaderData.brand}: até ${loaderData.reward}€ — Beer Money Club` },{ name:"description",content:loaderData.summary},{ property:"og:title",content:`${loaderData.brand}: até ${loaderData.reward}€`},{ property:"og:description",content:loaderData.summary},{ property:"og:type",content:"article"},{ name:"twitter:card",content:"summary_large_image"}] : [{title:"Oportunidade indisponível — Beer Money Club"},{name:"robots",content:"noindex"}] }),
  component: DetailPage,
});
function DetailPage(){const item=Route.useLoaderData();const [saved,setSaved]=useState(false);return <div className="app-frame"><header className="app-header"><Button asChild variant="ghost" size="icon" aria-label="Voltar"><Link to="/"><ArrowLeft/></Link></Button><span className="text-sm font-extrabold">Oportunidade</span><Button variant="ghost" size="icon" aria-label="Guardar" onClick={()=>setSaved(!saved)} className={saved?"text-primary":""}><Bookmark className={saved?"fill-current":""}/></Button></header><main className="safe-bottom pb-28"><section className="px-5 pt-5"><div className={`brand-tile accent-${item.accent}`}>{item.brand[0]}</div><p className="mt-6 text-sm font-extrabold text-muted-foreground">{item.brand} · {item.category}</p><h1 className="mt-2 font-editorial text-[38px] font-semibold leading-[1.02]">{item.title}</h1><p className="mt-4 text-base leading-6 text-muted-foreground">{item.summary}</p><div className="mt-7 flex items-end justify-between border-b pb-7"><div><p className="text-xs font-bold text-muted-foreground">VALOR ESPERADO</p><p className="mt-2 text-5xl font-extrabold">até {item.reward}€</p></div>{item.previousReward&&<span className="rounded-full bg-positive-soft px-3 py-1.5 text-xs font-bold text-positive">Subiu de {item.previousReward}€</span>}</div></section><section className="grid grid-cols-3 gap-px border-b bg-border"><div className="bg-background p-4"><Clock3 className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Tempo</p><strong className="text-sm">{item.time}</strong></div><div className="bg-background p-4"><ShieldCheck className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Dificuldade</p><strong className="text-sm">{item.difficulty}</strong></div><div className="bg-background p-4"><Bell className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Prazo</p><strong className="text-sm">{item.deadline.replace("Termina ","")}</strong></div></section><section className="px-5 py-7"><h2 className="text-xl font-extrabold">Como aproveitar</h2><ol className="mt-5 space-y-5">{item.steps.map((step,i)=><li key={step} className="flex gap-4"><span className="grid size-7 flex-none place-items-center rounded-full bg-accent text-xs font-extrabold text-primary">{i+1}</span><p className="pt-1 text-sm leading-5">{step}</p></li>)}</ol><div className="mt-8 flex gap-3 rounded-xl bg-muted p-4"><Check className="mt-0.5 size-5 flex-none text-positive"/><p className="text-xs leading-5 text-muted-foreground">Verificámos esta oportunidade hoje. Confirma sempre as condições finais no site da marca.</p></div></section></main><div className="fixed inset-x-0 bottom-0 z-40 mx-auto max-w-[540px] border-t bg-background/95 p-4 pb-[max(16px,env(safe-area-inset-bottom))] backdrop-blur"><Button asChild size="lg" className="h-13 w-full text-base"><a href={item.url} target="_blank" rel="noreferrer">Começar <ExternalLink/></a></Button></div></div>}
