import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Bell, Bookmark, Check, Clock3, ExternalLink, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { opportunities } from "@/lib/opportunities";
import { BrandLogo } from "@/components/beer-money/brand-logo";

export const Route = createFileRoute("/oportunidades/$id")({
  loader: ({ params }) => { const item=opportunities.find(o=>o.id===params.id); if(!item) throw notFound(); return item; },
  head: ({ loaderData }) => ({ meta: loaderData ? [{ title: `${loaderData.brand}: até ${loaderData.reward}€ — Beer Money Club` },{ name:"description",content:loaderData.summary},{ property:"og:title",content:`${loaderData.brand}: até ${loaderData.reward}€`},{ property:"og:description",content:loaderData.summary},{ property:"og:type",content:"article"},{ name:"twitter:card",content:"summary_large_image"}] : [{title:"Oportunidade indisponível — Beer Money Club"},{name:"robots",content:"noindex"}] }),
  component: DetailPage,
});
function DetailPage(){const item=Route.useLoaderData();const [saved,setSaved]=useState(false);return <div className="app-frame"><header className="app-header"><Button asChild variant="ghost" size="icon" aria-label="Voltar"><Link to="/"><ArrowLeft/></Link></Button><span className="text-sm font-bold">Oportunidade</span><Button variant="ghost" size="icon" aria-label="Guardar" onClick={()=>setSaved(!saved)} className={saved?"text-primary":""}><Bookmark className={saved?"fill-current":""}/></Button></header><main className="safe-bottom pb-28"><section className="px-5 pt-7"><BrandLogo name={item.brand} large/><p className="mt-6 text-[11px] font-bold uppercase text-muted-foreground">{item.category}</p><h1 className="mt-2 text-[42px] font-extrabold leading-none">{item.brand}</h1><h2 className="mt-4 text-2xl font-semibold leading-tight">{item.title}</h2><p className="mt-3 text-base leading-6 text-muted-foreground">{item.summary}</p><div className="mt-7 border-y py-5"><p className="text-xs font-semibold text-muted-foreground">Valor da oportunidade</p><div className="mt-1 flex items-end justify-between"><p className="text-3xl font-bold">Até {item.reward}€</p>{item.previousReward&&<span className="text-xs font-bold text-positive">Antes {item.previousReward}€</span>}</div></div></section><section className="px-5 py-6"><h2 className="text-lg font-extrabold">O essencial</h2><div className="mt-4 divide-y border-y"><div className="detail-row"><Clock3/><span>Tempo estimado</span><strong>{item.time}</strong></div><div className="detail-row"><ShieldCheck/><span>Dificuldade</span><strong>{item.difficulty}</strong></div><div className="detail-row"><Bell/><span>Prazo</span><strong>{item.deadline.replace("Termina ","")}</strong></div></div></section><section className="px-5 py-3"><h2 className="text-lg font-extrabold">Como aproveitar</h2><ol className="mt-5 space-y-5">{item.steps.map((step,i)=><li key={step} className="flex gap-4"><span className="step-number">{i+1}</span><p className="pt-1 text-sm leading-5">{step}</p></li>)}</ol><div className="mt-8 flex gap-3 border-t pt-5"><Check className="mt-0.5 size-5 flex-none text-positive"/><p className="text-xs leading-5 text-muted-foreground">Verificámos esta oportunidade hoje. Confirma sempre as condições finais no site da marca.</p></div></section></main><div className="bottom-action"><Button asChild size="lg" className="h-13 w-full text-base"><a href={item.url} target="_blank" rel="noreferrer">Abrir na {item.brand} <ExternalLink/></a></Button></div></div>}
