/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as ComoGanhamosDinheiroRouteImport } from './routes/como-ganhamos-dinheiro'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as InformacaoLegalRouteImport } from './routes/informacao-legal'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AdminVerificacoesRouteImport } from './routes/admin.verificacoes'
import { Route as OportunidadesIdRouteImport } from './routes/oportunidades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoGanhamosDinheiroRoute = ComoGanhamosDinheiroRouteImport.update({
  id: '/como-ganhamos-dinheiro',
  path: '/como-ganhamos-dinheiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const InformacaoLegalRoute = InformacaoLegalRouteImport.update({
  id: '/informacao-legal',
  path: '/informacao-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerificacoesRoute = AdminVerificacoesRouteImport.update({
  id: '/admin/verificacoes',
  path: '/admin/verificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIdRoute = OportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/como-ganhamos-dinheiro': typeof ComoGanhamosDinheiroRoute
  '/conta': typeof ContaRoute
  '/explorar': typeof ExplorarRoute
  '/informacao-legal': typeof InformacaoLegalRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/como-ganhamos-dinheiro': typeof ComoGanhamosDinheiroRoute
  '/conta': typeof ContaRoute
  '/explorar': typeof ExplorarRoute
  '/informacao-legal': typeof InformacaoLegalRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/como-ganhamos-dinheiro': typeof ComoGanhamosDinheiroRoute
  '/conta': typeof ContaRoute
  '/explorar': typeof ExplorarRoute
  '/informacao-legal': typeof InformacaoLegalRoute
  '/instalar': typeof InstalarRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin/verificacoes': typeof AdminVerificacoesRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/como-ganhamos-dinheiro'
    | '/conta'
    | '/explorar'
    | '/informacao-legal'
    | '/instalar'
    | '/login'
    | '/onboarding'
    | '/admin/verificacoes'
    | '/oportunidades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/como-ganhamos-dinheiro'
    | '/conta'
    | '/explorar'
    | '/informacao-legal'
    | '/instalar'
    | '/login'
    | '/onboarding'
    | '/admin/verificacoes'
    | '/oportunidades/$id'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/como-ganhamos-dinheiro'
    | '/conta'
    | '/explorar'
    | '/informacao-legal'
    | '/instalar'
    | '/login'
    | '/onboarding'
    | '/admin/verificacoes'
    | '/oportunidades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ComoGanhamosDinheiroRoute: typeof ComoGanhamosDinheiroRoute
  ContaRoute: typeof ContaRoute
  ExplorarRoute: typeof ExplorarRoute
  InformacaoLegalRoute: typeof InformacaoLegalRoute
  InstalarRoute: typeof InstalarRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AdminVerificacoesRoute: typeof AdminVerificacoesRoute
  OportunidadesIdRoute: typeof OportunidadesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ganhamos-dinheiro': {
      id: '/como-ganhamos-dinheiro'
      path: '/como-ganhamos-dinheiro'
      fullPath: '/como-ganhamos-dinheiro'
      preLoaderRoute: typeof ComoGanhamosDinheiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/informacao-legal': {
      id: '/informacao-legal'
      path: '/informacao-legal'
      fullPath: '/informacao-legal'
      preLoaderRoute: typeof InformacaoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verificacoes': {
      id: '/admin/verificacoes'
      path: '/admin/verificacoes'
      fullPath: '/admin/verificacoes'
      preLoaderRoute: typeof AdminVerificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/$id': {
      id: '/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof OportunidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ComoGanhamosDinheiroRoute: ComoGanhamosDinheiroRoute,
  ContaRoute: ContaRoute,
  ExplorarRoute: ExplorarRoute,
  InformacaoLegalRoute: InformacaoLegalRoute,
  InstalarRoute: InstalarRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AdminVerificacoesRoute: AdminVerificacoesRoute,
  OportunidadesIdRoute: OportunidadesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
